In [3]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [7]:
games = pd.read_csv("../data/raw/Video_Games_Sales_as_at_22_Dec_2016.csv")

steam = pd.read_csv("../data/raw/merged_data.csv")

In [8]:
games.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
steam.head()

,Title,Original Price,Discounted Price,Release Date,Link,Game Description,Recent Reviews Summary,All Reviews Summary,Recent Reviews Number,All Reviews Number,Developer,Publisher,Supported Languages,Popular Tags,Game Features,Minimum Requirements
0,Baldur's Gate 3,$29.99,$29.99,"3 Aug, 2023",https://store.steampowered.com/app/1086940/Bal...,"Baldur’s Gate 3 is a story-rich, party-based R...",Overwhelmingly Positive,Very Positive,"- 96% of the 128,900 user reviews in the last ...","- 94% of the 188,617 user reviews for this gam...",Larian Studios,Larian Studios,"['English', 'French', 'German', 'Spanish - Spa...","['RPG', 'Choices Matter', 'Character Customiza...","['Single-player', 'Online Co-op', 'LAN Co-op',...",Requires a 64-bit processor and operating syst...
1,Counter-Strike: Global Offensive,$14.99,$14.99,"21 Aug, 2012",https://store.steampowered.com/app/730/Counter...,Counter-Strike: Global Offensive (CS: GO) expa...,Very Positive,Very Positive,"- 89% of the 75,284 user reviews in the last 3...","- 88% of the 7,428,921 user reviews for this g...","Valve, Hidden Path Entertainment",Valve,"['English', 'Czech', 'Danish', 'Dutch', 'Finni...","['FPS', 'Shooter', 'Multiplayer', 'Competitive...","['Steam Achievements', 'Full controller suppor...",OS: | Windows® 7/Vista/XP | Processor: | Int...
2,Apex Legends™,Free,Free,"4 Nov, 2020",https://store.steampowered.com/app/1172470/Ape...,"Apex Legends is the award-winning, free-to-pla...",Mixed,Very Positive,"- 65% of the 18,581 user reviews in the last 3...","- 80% of the 701,597 user reviews for this gam...",Respawn Entertainment,Electronic Arts,"['English', 'French', 'Italian', 'German', 'Sp...","['Free to Play', 'Multiplayer', 'Battle Royale...","['Online PvP', 'Online Co-op', 'Steam Achievem...",Requires a 64-bit processor and operating syst...
3,Forza Horizon 5,$34.78,$17.39,"8 Nov, 2021",https://store.steampowered.com/app/1551360/For...,Your Ultimate Horizon Adventure awaits! Explor...,Very Positive,Very Positive,"- 87% of the 4,120 user reviews in the last 30...","- 88% of the 123,162 user reviews for this gam...",Playground Games,Xbox Game Studios,"['English', 'French', 'Italian', 'German', 'Sp...","['Racing', 'Open World', 'Driving', 'Multiplay...","['Single-player', 'Online PvP', 'Online Co-op'...",Requires a 64-bit processor and operating syst...
4,Call of Duty®,Free,Free,"27 Oct, 2022",https://store.steampowered.com/app/1938090/Cal...,"Welcome to Call of Duty® HQ, the home of Call ...",Mixed,Mixed,"- 49% of the 8,257 user reviews in the last 30...","- 57% of the 236,876 user reviews for this gam...","Infinity Ward, Raven Software, Beenox, Treyarc...",Activision,"['English', 'French', 'Italian', 'German', 'Sp...","['FPS', 'Multiplayer', 'Shooter', 'Action', 'S...","['Single-player', 'Online PvP', 'Online Co-op'...",Requires a 64-bit processor and operating syst...

In [10]:
games.shape

(16719, 16)

In [11]:
steam.shape

(71700, 16)

In [12]:
games.columns

Index(['Name', 'Platform', 'Year_of_Release', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales', 'Critic_Score',
       'Critic_Count', 'User_Score', 'User_Count', 'Developer', 'Rating'],
      dtype='str')

In [13]:
steam.columns

Index(['Title', 'Original Price', 'Discounted Price', 'Release Date', 'Link',
       'Game Description', 'Recent Reviews Summary', 'All Reviews Summary',
       'Recent Reviews Number', 'All Reviews Number', 'Developer', 'Publisher',
       'Supported Languages', 'Popular Tags', 'Game Features',
       'Minimum Requirements'],
      dtype='str')

In [14]:
games.info()

<class 'pandas.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16717 non-null  str
 1   Platform         16719 non-null  str
 2   Year_of_Release  16450 non-null  float64
 3   Genre            16717 non-null  str
 4   Publisher        16665 non-null  str
 5   NA_Sales         16719 non-null  float64
 6   EU_Sales         16719 non-null  float64
 7   JP_Sales         16719 non-null  float64
 8   Other_Sales      16719 non-null  float64
 9   Global_Sales     16719 non-null  float64
 10  Critic_Score     8137 non-null   float64
 11  Critic_Count     8137 non-null   float64
 12  User_Score       10015 non-null  str
 13  User_Count       7590 non-null   float64
 14  Developer        10096 non-null  str
 15  Rating           9950 non-null   str
dtypes: float64(9), str(7)
memory usage: 3.0 MB

In [15]:
steam.info()

<class 'pandas.DataFrame'>
RangeIndex: 71700 entries, 0 to 71699
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Title                   71699 non-null  str
 1   Original Price          71700 non-null  str
 2   Discounted Price        71700 non-null  str
 3   Release Date            71569 non-null  str
 4   Link                    71700 non-null  str
 5   Game Description        71489 non-null  str
 6   Recent Reviews Summary  56480 non-null  str
 7   All Reviews Summary     5371 non-null   str
 8   Recent Reviews Number   56480 non-null  str
 9   All Reviews Number      5371 non-null   str
 10  Developer               71479 non-null  str
 11  Publisher               71183 non-null  str
 12  Supported Languages     71700 non-null  str
 13  Popular Tags            71700 non-null  str
 14  Game Features           71700 non-null  str
 15  Minimum Requirements    70576 non-null  str
dtypes: str(16)
memory usage: 71.8 MB

In [16]:
games.describe(include='all')

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
count,16717,16719,16450.000000,16717,16665,16719.000000,16719.000000,16719.000000,16719.000000,16719.000000,8137.000000,8137.000000,10015,7590.000000,10096,9950
unique,11562,31,NaN,12,581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96,NaN,1696,8
top,Need for Speed: Most Wanted,PS2,NaN,Action,Electronic Arts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tbd,NaN,Ubisoft,E
freq,12,2161,NaN,3370,1356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2425,NaN,204,3991
mean,NaN,NaN,2006.487356,NaN,NaN,0.263330,0.145025,0.077602,0.047332,0.533543,68.967679,26.360821,NaN,162.229908,NaN,NaN
std,NaN,NaN,5.878995,NaN,NaN,0.813514,0.503283,0.308818,0.186710,1.547935,13.938165,18.980495,NaN,561.282326,NaN,NaN
min,NaN,NaN,1980.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.010000,13.000000,3.000000,NaN,4.000000,NaN,NaN
25%,NaN,NaN,2003.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.060000,60.000000,12.000000,NaN,10.000000,NaN,NaN
50%,NaN,NaN,2007.000000,NaN,NaN,0.080000,0.020000,0.000000,0.010000,0.170000,71.000000,21.000000,NaN,24.000000,NaN,NaN
75%,NaN,NaN,2010.000000,NaN,NaN,0.240000,0.110000,0.040000,0.030000,0.470000,79.000000,36.000000,NaN,81.000000,NaN,NaN
max,NaN,NaN,2020.000000,NaN,NaN,41.360000,28.960000,10.220000,10.570000,82.530000,98.000000,113.000000,NaN,10665.000000,NaN,NaN

In [17]:
steam.describe(include='all')

,Title,Original Price,Discounted Price,Release Date,Link,Game Description,Recent Reviews Summary,All Reviews Summary,Recent Reviews Number,All Reviews Number,Developer,Publisher,Supported Languages,Popular Tags,Game Features,Minimum Requirements
count,71699,71700,71700,71569,71700,71489,56480,5371,56480,5371,71479,71183,71700,71700,71700,70576
unique,71699,654,827,4441,71700,71090,18,7,13391,5296,45353,38543,11058,65817,5418,63201
top,Baldur's Gate 3,Free,Free,Coming soon,https://store.steampowered.com/app/1086940/Bal...,Find the objects that are hidden on the map.,Very Positive,Very Positive,- Need more user reviews to generate a score,- 90% of the 624 user reviews for this game ar...,Choice of Games,Big Fish Games,['English'],"['Indie', 'Casual']",['Single-player'],Requires a 64-bit processor and operating syst...
freq,1,17585,17585,5887,1,34,11039,3151,18999,3,162,459,38083,284,17262,274

In [18]:
games.nunique()

Name               11562
Platform              31
Year_of_Release       39
Genre                 12
Publisher            581
NA_Sales             402
EU_Sales             307
JP_Sales             244
Other_Sales          155
Global_Sales         629
Critic_Score          82
Critic_Count         106
User_Score            96
User_Count           888
Developer           1696
Rating                 8
dtype: int64

In [19]:
steam.nunique()

Title                     71699
Original Price              654
Discounted Price            827
Release Date               4441
Link                      71700
Game Description          71090
Recent Reviews Summary       18
All Reviews Summary           7
Recent Reviews Number     13391
All Reviews Number         5296
Developer                 45353
Publisher                 38543
Supported Languages       11058
Popular Tags              65817
Game Features              5418
Minimum Requirements      63201
dtype: int64

In [20]:
games.isnull().sum().sort_values(ascending=False)

User_Count         9129
Critic_Count       8582
Critic_Score       8582
Rating             6769
User_Score         6704
Developer          6623
Year_of_Release     269
Publisher            54
Name                  2
Genre                 2
NA_Sales              0
Platform              0
JP_Sales              0
EU_Sales              0
Other_Sales           0
Global_Sales          0
dtype: int64

In [21]:
steam.isnull().sum().sort_values(ascending=False)

All Reviews Summary       66329
All Reviews Number        66329
Recent Reviews Number     15220
Recent Reviews Summary    15220
Minimum Requirements       1124
Publisher                   517
Developer                   221
Game Description            211
Release Date                131
Title                         1
Original Price                0
Discounted Price              0
Link                          0
Supported Languages           0
Popular Tags                  0
Game Features                 0
dtype: int64

In [22]:
(games.isnull().mean() * 100).sort_values(ascending=False).round(2)

User_Count         54.60
Critic_Count       51.33
Critic_Score       51.33
Rating             40.49
User_Score         40.10
Developer          39.61
Year_of_Release     1.61
Publisher           0.32
Name                0.01
Genre               0.01
NA_Sales            0.00
Platform            0.00
JP_Sales            0.00
EU_Sales            0.00
Other_Sales         0.00
Global_Sales        0.00
dtype: float64

In [23]:
(steam.isnull().mean() * 100).sort_values(ascending=False).round(2)

All Reviews Summary       92.51
All Reviews Number        92.51
Recent Reviews Number     21.23
Recent Reviews Summary    21.23
Minimum Requirements       1.57
Publisher                  0.72
Developer                  0.31
Game Description           0.29
Release Date               0.18
Title                      0.00
Original Price             0.00
Discounted Price           0.00
Link                       0.00
Supported Languages        0.00
Popular Tags               0.00
Game Features              0.00
dtype: float64

In [24]:
games.duplicated().sum()

np.int64(0)

In [25]:
steam.duplicated().sum()

np.int64(0)

In [26]:
games.describe()

,Year_of_Release,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Count
count,16450.000000,16719.000000,16719.000000,16719.000000,16719.000000,16719.000000,8137.000000,8137.000000,7590.000000
mean,2006.487356,0.263330,0.145025,0.077602,0.047332,0.533543,68.967679,26.360821,162.229908
std,5.878995,0.813514,0.503283,0.308818,0.186710,1.547935,13.938165,18.980495,561.282326
min,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000,13.000000,3.000000,4.000000
25%,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000,60.000000,12.000000,10.000000
50%,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000,71.000000,21.000000,24.000000
75%,2010.000000,0.240000,0.110000,0.040000,0.030000,0.470000,79.000000,36.000000,81.000000
max,2020.000000,41.360000,28.960000,10.220000,10.570000,82.530000,98.000000,113.000000,10665.000000

In [27]:
games['Genre'].value_counts()

Genre
Action          3370
Sports          2348
Misc            1750
Role-Playing    1500
Shooter         1323
Adventure       1303
Racing          1249
Platform         888
Simulation       874
Fighting         849
Strategy         683
Puzzle           580
Name: count, dtype: int64

In [28]:
games['Platform'].value_counts()

Platform
PS2     2161
DS      2152
PS3     1331
Wii     1320
X360    1262
PSP     1209
PS      1197
PC       974
XB       824
GBA      822
GC       556
3DS      520
PSV      432
PS4      393
N64      319
XOne     247
SNES     239
SAT      173
WiiU     147
2600     133
NES       98
GB        98
DC        52
GEN       29
NG        12
SCD        6
WS         6
3DO        3
TG16       2
GG         1
PCFX       1
Name: count, dtype: int64

In [29]:
games['Rating'].value_counts(dropna=False)

Rating
NaN     6769
E       3991
T       2961
M       1563
E10+    1420
EC         8
K-A        3
RP         3
AO         1
Name: count, dtype: int64

In [30]:
steam['Recent Reviews Summary'].value_counts(dropna=False)

Recent Reviews Summary
NaN                        15220
Very Positive              11039
Mixed                       9164
Positive                    8456
Mostly Positive             6738
1 user reviews              4107
2 user reviews              3169
3 user reviews              2608
4 user reviews              2147
5 user reviews              1799
6 user reviews              1508
7 user reviews              1409
Mostly Negative             1352
8 user reviews              1213
9 user reviews              1039
Overwhelmingly Positive      443
Negative                     236
Very Negative                 43
Overwhelmingly Negative       10
Name: count, dtype: int64

In [31]:
steam['All Reviews Summary'].value_counts(dropna=False)

All Reviews Summary
NaN                        66329
Very Positive               3151
Overwhelmingly Positive      852
Mostly Positive              783
Mixed                        505
Positive                      56
Mostly Negative               21
Overwhelmingly Negative        3
Name: count, dtype: int64

In [32]:
games['User_Score'].unique()

<ArrowStringArray>
[  '8',   nan, '8.3', '8.5', '6.6', '8.4', '8.6', '7.7', '6.3', '7.4', '8.2',
   '9', '7.9', '8.1', '8.7', '7.1', '3.4', '5.3', '4.8', '3.2', '8.9', '6.4',
 '7.8', '7.5', '2.6', '7.2', '9.2',   '7', '7.3', '4.3', '7.6', '5.7',   '5',
 '9.1', '6.5', 'tbd', '8.8', '6.9', '9.4', '6.8', '6.1', '6.7', '5.4',   '4',
 '4.9', '4.5', '9.3', '6.2', '4.2',   '6', '3.7', '4.1', '5.8', '5.6', '5.5',
 '4.4', '4.6', '5.9', '3.9', '3.1', '2.9', '5.2', '3.3', '4.7', '5.1', '3.5',
 '2.5', '1.9',   '3', '2.7', '2.2',   '2', '9.5', '2.1', '3.6', '2.8', '1.8',
 '3.8',   '0', '1.6', '9.6', '2.4', '1.7', '1.1', '0.3', '1.5', '0.7', '1.2',
 '2.3', '0.5', '1.3', '0.2', '0.6', '1.4', '0.9',   '1', '9.7']
Length: 97, dtype: str

In [33]:
sorted(games['User_Score'].dropna().unique())

['0',
 '0.2',
 '0.3',
 '0.5',
 '0.6',
 '0.7',
 '0.9',
 '1',
 '1.1',
 '1.2',
 '1.3',
 '1.4',
 '1.5',
 '1.6',
 '1.7',
 '1.8',
 '1.9',
 '2',
 '2.1',
 '2.2',
 '2.3',
 '2.4',
 '2.5',
 '2.6',
 '2.7',
 '2.8',
 '2.9',
 '3',
 '3.1',
 '3.2',
 '3.3',
 '3.4',
 '3.5',
 '3.6',
 '3.7',
 '3.8',
 '3.9',
 '4',
 '4.1',
 '4.2',
 '4.3',
 '4.4',
 '4.5',
 '4.6',
 '4.7',
 '4.8',
 '4.9',
 '5',
 '5.1',
 '5.2',
 '5.3',
 '5.4',
 '5.5',
 '5.6',
 '5.7',
 '5.8',
 '5.9',
 '6',
 '6.1',
 '6.2',
 '6.3',
 '6.4',
 '6.5',
 '6.6',
 '6.7',
 '6.8',
 '6.9',
 '7',
 '7.1',
 '7.2',
 '7.3',
 '7.4',
 '7.5',
 '7.6',
 '7.7',
 '7.8',
 '7.9',
 '8',
 '8.1',
 '8.2',
 '8.3',
 '8.4',
 '8.5',
 '8.6',
 '8.7',
 '8.8',
 '8.9',
 '9',
 '9.1',
 '9.2',
 '9.3',
 '9.4',
 '9.5',
 '9.6',
 '9.7',
 'tbd']

In [34]:
steam['Original Price'].value_counts().head(20)

Original Price
Free      17585
$0.90      5726
$3.29      5689
$6.29      4839
$1.39      4168
$2.19      3651
$2.69      2527
$8.49      2514
$10.49     2267
$4.99      2251
$3.99      2222
$6.99      2075
$4.69      1725
$2.99      1319
$12.49      858
$9.99       804
$7.49       801
$5.79       749
$1.99       644
$14.49      616
Name: count, dtype: int64

In [35]:
steam['Discounted Price'].value_counts().head(20)

Discounted Price
Free      17585
$0.90      5481
$3.29      5477
$6.29      4717
$1.39      4022
$2.19      3562
$2.69      2424
$8.49      2412
$4.99      2180
$10.49     2171
$3.99      2149
$6.99      2021
$4.69      1672
$2.99      1289
$12.49      818
$7.49       789
$9.99       784
$5.79       717
$1.99       649
$14.49      589
Name: count, dtype: int64

In [36]:
steam['Release Date'].head(20)

0      3 Aug, 2023
1     21 Aug, 2012
2      4 Nov, 2020
3      8 Nov, 2021
4     27 Oct, 2022
5     21 Dec, 2017
6     25 Jul, 2023
7      9 Dec, 2020
8      8 Feb, 2018
9     11 Aug, 2021
10    13 Apr, 2015
11     1 Dec, 2015
12    14 Jun, 2016
13    10 Oct, 2007
14     9 Jul, 2013
15    15 Aug, 2013
16    18 Feb, 2014
17    22 May, 2017
18    25 Mar, 2013
19    15 Jun, 2023
Name: Release Date, dtype: str