In [2]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

steam = pd.read_csv("../data/raw/merged_data.csv")

steam_clean = steam.copy()

In [3]:
steam_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 71700 entries, 0 to 71699
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Title                   71699 non-null  str
 1   Original Price          71700 non-null  str
 2   Discounted Price        71700 non-null  str
 3   Release Date            71569 non-null  str
 4   Link                    71700 non-null  str
 5   Game Description        71489 non-null  str
 6   Recent Reviews Summary  56480 non-null  str
 7   All Reviews Summary     5371 non-null   str
 8   Recent Reviews Number   56480 non-null  str
 9   All Reviews Number      5371 non-null   str
 10  Developer               71479 non-null  str
 11  Publisher               71183 non-null  str
 12  Supported Languages     71700 non-null  str
 13  Popular Tags            71700 non-null  str
 14  Game Features           71700 non-null  str
 15  Minimum Requirements    70576 non-null  str
dtypes: str(16)
memory usage: 71.8 MB

In [4]:
steam_clean.isnull().sum()

Title                         1
Original Price                0
Discounted Price              0
Release Date                131
Link                          0
Game Description            211
Recent Reviews Summary    15220
All Reviews Summary       66329
Recent Reviews Number     15220
All Reviews Number        66329
Developer                   221
Publisher                   517
Supported Languages           0
Popular Tags                  0
Game Features                 0
Minimum Requirements       1124
dtype: int64

In [5]:
steam_clean.duplicated().sum()

np.int64(0)

In [6]:
steam_clean.head()

,Title,Original Price,Discounted Price,Release Date,Link,Game Description,Recent Reviews Summary,All Reviews Summary,Recent Reviews Number,All Reviews Number,Developer,Publisher,Supported Languages,Popular Tags,Game Features,Minimum Requirements
0,Baldur's Gate 3,$29.99,$29.99,"3 Aug, 2023",https://store.steampowered.com/app/1086940/Bal...,"Baldur’s Gate 3 is a story-rich, party-based R...",Overwhelmingly Positive,Very Positive,"- 96% of the 128,900 user reviews in the last ...","- 94% of the 188,617 user reviews for this gam...",Larian Studios,Larian Studios,"['English', 'French', 'German', 'Spanish - Spa...","['RPG', 'Choices Matter', 'Character Customiza...","['Single-player', 'Online Co-op', 'LAN Co-op',...",Requires a 64-bit processor and operating syst...
1,Counter-Strike: Global Offensive,$14.99,$14.99,"21 Aug, 2012",https://store.steampowered.com/app/730/Counter...,Counter-Strike: Global Offensive (CS: GO) expa...,Very Positive,Very Positive,"- 89% of the 75,284 user reviews in the last 3...","- 88% of the 7,428,921 user reviews for this g...","Valve, Hidden Path Entertainment",Valve,"['English', 'Czech', 'Danish', 'Dutch', 'Finni...","['FPS', 'Shooter', 'Multiplayer', 'Competitive...","['Steam Achievements', 'Full controller suppor...",OS: | Windows® 7/Vista/XP | Processor: | Int...
2,Apex Legends™,Free,Free,"4 Nov, 2020",https://store.steampowered.com/app/1172470/Ape...,"Apex Legends is the award-winning, free-to-pla...",Mixed,Very Positive,"- 65% of the 18,581 user reviews in the last 3...","- 80% of the 701,597 user reviews for this gam...",Respawn Entertainment,Electronic Arts,"['English', 'French', 'Italian', 'German', 'Sp...","['Free to Play', 'Multiplayer', 'Battle Royale...","['Online PvP', 'Online Co-op', 'Steam Achievem...",Requires a 64-bit processor and operating syst...
3,Forza Horizon 5,$34.78,$17.39,"8 Nov, 2021",https://store.steampowered.com/app/1551360/For...,Your Ultimate Horizon Adventure awaits! Explor...,Very Positive,Very Positive,"- 87% of the 4,120 user reviews in the last 30...","- 88% of the 123,162 user reviews for this gam...",Playground Games,Xbox Game Studios,"['English', 'French', 'Italian', 'German', 'Sp...","['Racing', 'Open World', 'Driving', 'Multiplay...","['Single-player', 'Online PvP', 'Online Co-op'...",Requires a 64-bit processor and operating syst...
4,Call of Duty®,Free,Free,"27 Oct, 2022",https://store.steampowered.com/app/1938090/Cal...,"Welcome to Call of Duty® HQ, the home of Call ...",Mixed,Mixed,"- 49% of the 8,257 user reviews in the last 30...","- 57% of the 236,876 user reviews for this gam...","Infinity Ward, Raven Software, Beenox, Treyarc...",Activision,"['English', 'French', 'Italian', 'German', 'Sp...","['FPS', 'Multiplayer', 'Shooter', 'Action', 'S...","['Single-player', 'Online PvP', 'Online Co-op'...",Requires a 64-bit processor and operating syst...

In [7]:
steam_clean[steam_clean['Title'].isnull()]

,Title,Original Price,Discounted Price,Release Date,Link,Game Description,Recent Reviews Summary,All Reviews Summary,Recent Reviews Number,All Reviews Number,Developer,Publisher,Supported Languages,Popular Tags,Game Features,Minimum Requirements
56954,NaN,Free,Free,NaN,https://store.steampowered.com/sub/418/?snr=1_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],[],[],NaN

In [8]:
steam_clean['Original Price'].value_counts().head(20)

Original Price
Free      17585
$0.90      5726
$3.29      5689
$6.29      4839
$1.39      4168
$2.19      3651
$2.69      2527
$8.49      2514
$10.49     2267
$4.99      2251
$3.99      2222
$6.99      2075
$4.69      1725
$2.99      1319
$12.49      858
$9.99       804
$7.49       801
$5.79       749
$1.99       644
$14.49      616
Name: count, dtype: int64

In [9]:
steam_clean['Discounted Price'].value_counts().head(20)

Discounted Price
Free      17585
$0.90      5481
$3.29      5477
$6.29      4717
$1.39      4022
$2.19      3562
$2.69      2424
$8.49      2412
$4.99      2180
$10.49     2171
$3.99      2149
$6.99      2021
$4.69      1672
$2.99      1289
$12.49      818
$7.49       789
$9.99       784
$5.79       717
$1.99       649
$14.49      589
Name: count, dtype: int64

In [10]:
steam_clean = steam_clean.dropna(subset=['Title'])

In [11]:
steam_clean['Title'].isnull().sum()

np.int64(0)

In [15]:
steam_clean[steam_clean['Original Price'].str.contains(',', na=False)][['Original Price']].drop_duplicates()

       Original Price
13889       $1,999.98
25828       $1,045.83
31968       $1,101.77
36602       $1,000.00
38641       $1,189.77
39897     $100,000.00
47398       $1,234.57
52064  $14,046,333.00
63158       $9,999.00

In [16]:
steam_clean[steam_clean['Discounted Price'].str.contains(',', na=False)][['Discounted Price']].drop_duplicates()

      Discounted Price
13889        $1,999.98
36602        $1,000.00
39897      $100,000.00
47398        $1,234.57
52064    $4,213,899.90
63158        $9,999.00

In [17]:
steam_clean['Original Price'] = (
    steam_clean['Original Price']
    .replace('Free', '0')
    .str.replace('$', '', regex=False)
    .str.replace(',', '', regex=False)
)

steam_clean['Original Price'] = pd.to_numeric(steam_clean['Original Price'])

In [20]:
steam_clean[['Original Price', 'Discounted Price']].dtypes

Original Price      float64
Discounted Price        str
dtype: object

In [21]:
temp = (
    steam_clean['Discounted Price']
    .replace('Free', '0')
    .str.replace('$', '', regex=False)
    .str.replace(',', '', regex=False)
)

pd.to_numeric(temp, errors='coerce')[pd.to_numeric(temp, errors='coerce').isna()]

Series([], Name: Discounted Price, dtype: float64)

In [22]:
steam_clean.loc[
    pd.to_numeric(temp, errors='coerce').isna(),
    'Discounted Price'
].drop_duplicates()

Series([], Name: Discounted Price, dtype: str)

In [23]:
steam_clean['Discounted Price'] = pd.to_numeric(
    steam_clean['Discounted Price']
        .replace('Free', '0')
        .str.replace('$', '', regex=False)
        .str.replace(',', '', regex=False),
    errors='raise'
)

In [24]:
steam_clean['Discounted Price'].dtype

dtype('float64')

In [25]:
steam_clean['Discount Percentage'] = np.where(
    steam_clean['Original Price'] > 0,
    ((steam_clean['Original Price'] - steam_clean['Discounted Price'])
     / steam_clean['Original Price']) * 100,
    0
)

steam_clean['Discount Percentage'] = steam_clean['Discount Percentage'].round(2)

In [26]:
steam_clean[['Original Price',
             'Discounted Price',
             'Discount Percentage']].head(10)

   Original Price  Discounted Price  Discount Percentage
0           29.99             29.99                 0.00
1           14.99             14.99                 0.00
2            0.00              0.00                 0.00
3           34.78             17.39                50.00
4            0.00              0.00                 0.00
5            0.00              0.00                 0.00
6           34.99             34.99                 0.00
7           29.99             14.99                50.02
8           19.99             19.99                 0.00
9            0.00              0.00                 0.00

In [27]:
steam_clean['Is Free'] = steam_clean['Original Price'] == 0

In [28]:
steam_clean['Release Date'].head(20)

0      3 Aug, 2023
1     21 Aug, 2012
2      4 Nov, 2020
3      8 Nov, 2021
4     27 Oct, 2022
5     21 Dec, 2017
6     25 Jul, 2023
7      9 Dec, 2020
8      8 Feb, 2018
9     11 Aug, 2021
10    13 Apr, 2015
11     1 Dec, 2015
12    14 Jun, 2016
13    10 Oct, 2007
14     9 Jul, 2013
15    15 Aug, 2013
16    18 Feb, 2014
17    22 May, 2017
18    25 Mar, 2013
19    15 Jun, 2023
Name: Release Date, dtype: str

In [29]:
steam_clean['Release Date'].sample(20, random_state=42)

36416    27 Jul, 2018
60977     Coming soon
64202    19 Feb, 2022
42453    12 Jan, 2022
70104     Coming soon
35966    22 Mar, 2017
29528     9 Aug, 2022
52114    27 Feb, 2018
50349     9 Mar, 2020
40890    15 Jun, 2021
56934     Coming soon
21336    14 Dec, 2019
33774    31 Jan, 2018
31141    23 Nov, 2015
19864     4 Mar, 2021
36260    19 Jun, 2022
66595     Coming soon
4845     29 Jul, 2021
49347     3 Jan, 2020
30855    24 Nov, 2016
Name: Release Date, dtype: str

In [30]:
(steam_clean['Release Date'] == 'Coming soon').sum()

np.int64(5887)

In [31]:
steam_clean['Release Date'] = pd.to_datetime(
    steam_clean['Release Date'],
    format='%d %b, %Y',
    errors='coerce'
)

In [32]:
steam_clean['Release Date'].dtype

dtype('<M8[us]')

In [33]:
steam_clean['Release Date'].isnull().sum()

np.int64(10305)

In [34]:
steam_clean['Release Year'] = steam_clean['Release Date'].dt.year

steam_clean['Release Month'] = steam_clean['Release Date'].dt.month_name()

In [35]:
steam_clean['Release Status'] = np.where(
    steam_clean['Release Date'].isna(),
    'Coming Soon',
    'Released'
)

In [36]:
steam.loc[
    pd.to_datetime(
        steam['Release Date'],
        format='%d %b, %Y',
        errors='coerce'
    ).isna(),
    'Release Date'
].value_counts().head(20)

Release Date
Coming soon        5887
To be announced    1809
2023                787
Q4 2023             392
2024                388
Q3 2023             138
Q1 2024             118
October 2023         78
September 2023       69
August 2023          59
Q2 2024              53
December 2023        41
Q4 2024              34
November 2023        34
2025                 27
Q3 2024              26
January 2024         18
June 2024            12
March 2024           12
February 2024        11
Name: count, dtype: int64

In [37]:
steam_clean['Release Month Number'] = steam_clean['Release Date'].dt.month

In [39]:
steam_clean['Recent Reviews Number'].dropna().head(10)

0    - 96% of the 128,900 user reviews in the last ...
1    - 89% of the 75,284 user reviews in the last 3...
2    - 65% of the 18,581 user reviews in the last 3...
3    - 87% of the 4,120 user reviews in the last 30...
4    - 49% of the 8,257 user reviews in the last 30...
5    - 64% of the 13,945 user reviews in the last 3...
6    - 82% of the 19,384 user reviews for this game...
7    - 90% of the 5,312 user reviews in the last 30...
8    - 86% of the 10,393 user reviews in the last 3...
9    - 75% of the 146,529 user reviews for this gam...
Name: Recent Reviews Number, dtype: str

In [40]:
steam_clean['All Reviews Number'].dropna().head(10)

0     - 94% of the 188,617 user reviews for this gam...
1     - 88% of the 7,428,921 user reviews for this g...
2     - 80% of the 701,597 user reviews for this gam...
3     - 88% of the 123,162 user reviews for this gam...
4     - 57% of the 236,876 user reviews for this gam...
5     - 57% of the 2,209,987 user reviews for this g...
7     - 80% of the 552,224 user reviews for this gam...
8     - 87% of the 781,742 user reviews for this gam...
10    - 86% of the 1,472,644 user reviews for this g...
11    - 86% of the 985,871 user reviews for this gam...
Name: All Reviews Number, dtype: str

In [41]:
steam_clean['Recent Review %'] = (
    steam_clean['Recent Reviews Number']
    .str.extract(r'(\d+)%')
    .astype(float)
)

In [42]:
steam_clean['Recent Review Count'] = (
    steam_clean['Recent Reviews Number']
    .str.extract(r'([\d,]+)\s+user reviews')[0]
    .str.replace(',', '', regex=False)
    .astype(float)
)

In [43]:
steam_clean['All Review %'] = (
    steam_clean['All Reviews Number']
    .str.extract(r'(\d+)%')
    .astype(float)
)

In [44]:
steam_clean['All Review Count'] = (
    steam_clean['All Reviews Number']
    .str.extract(r'([\d,]+)\s+user reviews')[0]
    .str.replace(',', '', regex=False)
    .astype(float)
)

In [45]:
steam_clean[
    [
        'Recent Reviews Number',
        'Recent Review %',
        'Recent Review Count',
        'All Reviews Number',
        'All Review %',
        'All Review Count'
    ]
].head(10)

,Recent Reviews Number,Recent Review %,Recent Review Count,All Reviews Number,All Review %,All Review Count
0,"- 96% of the 128,900 user reviews in the last ...",96.0,128900.0,"- 94% of the 188,617 user reviews for this gam...",94.0,188617.0
1,"- 89% of the 75,284 user reviews in the last 3...",89.0,75284.0,"- 88% of the 7,428,921 user reviews for this g...",88.0,7428921.0
2,"- 65% of the 18,581 user reviews in the last 3...",65.0,18581.0,"- 80% of the 701,597 user reviews for this gam...",80.0,701597.0
3,"- 87% of the 4,120 user reviews in the last 30...",87.0,4120.0,"- 88% of the 123,162 user reviews for this gam...",88.0,123162.0
4,"- 49% of the 8,257 user reviews in the last 30...",49.0,8257.0,"- 57% of the 236,876 user reviews for this gam...",57.0,236876.0
5,"- 64% of the 13,945 user reviews in the last 3...",64.0,13945.0,"- 57% of the 2,209,987 user reviews for this g...",57.0,2209987.0
6,"- 82% of the 19,384 user reviews for this game...",82.0,19384.0,NaN,NaN,NaN
7,"- 90% of the 5,312 user reviews in the last 30...",90.0,5312.0,"- 80% of the 552,224 user reviews for this gam...",80.0,552224.0
8,"- 86% of the 10,393 user reviews in the last 3...",86.0,10393.0,"- 87% of the 781,742 user reviews for this gam...",87.0,781742.0
9,"- 75% of the 146,529 user reviews for this gam...",75.0,146529.0,NaN,NaN,NaN

In [46]:
steam_clean.info()

<class 'pandas.DataFrame'>
Index: 71699 entries, 0 to 71699
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Title                   71699 non-null  str
 1   Original Price          71699 non-null  float64
 2   Discounted Price        71699 non-null  float64
 3   Release Date            61394 non-null  datetime64[us]
 4   Link                    71699 non-null  str
 5   Game Description        71489 non-null  str
 6   Recent Reviews Summary  56480 non-null  str
 7   All Reviews Summary     5371 non-null   str
 8   Recent Reviews Number   56480 non-null  str
 9   All Reviews Number      5371 non-null   str
 10  Developer               71479 non-null  str
 11  Publisher               71183 non-null  str
 12  Supported Languages     71699 non-null  str
 13  Popular Tags            71699 non-null  str
 14  Game Features           71699 non-null  str
 15  Minimum Requirements    70576 non-null  str
 16  Discount Percentage     71699 non-null  float64
 17  Is Free                 71699 non-null  bool
 18  Release Year            61394 non-null  float64
 19  Release Month           61394 non-null  str
 20  Release Status          71699 non-null  str
 21  Release Month Number    61394 non-null  float64
 22  Recent Review %         37481 non-null  float64
 23  Recent Review Count     37481 non-null  float64
 24  All Review %            5371 non-null   float64
 25  All Review Count        5371 non-null   float64
dtypes: bool(1), datetime64[us](1), float64(9), str(15)
memory usage: 76.9 MB

In [47]:
steam_clean.isnull().sum().sort_values(ascending=False)

All Reviews Summary       66328
All Reviews Number        66328
All Review %              66328
All Review Count          66328
Recent Review %           34218
Recent Review Count       34218
Recent Reviews Number     15219
Recent Reviews Summary    15219
Release Date              10305
Release Month Number      10305
Release Month             10305
Release Year              10305
Minimum Requirements       1123
Publisher                   516
Developer                   220
Game Description            210
Title                         0
Original Price                0
Discounted Price              0
Link                          0
Is Free                       0
Popular Tags                  0
Supported Languages           0
Discount Percentage           0
Game Features                 0
Release Status                0
dtype: int64

In [48]:
columns_to_drop = [
    'Recent Reviews Number',
    'All Reviews Number'
]

steam_clean.drop(columns=columns_to_drop, inplace=True)

In [49]:
steam_clean.info()

<class 'pandas.DataFrame'>
Index: 71699 entries, 0 to 71699
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Title                   71699 non-null  str
 1   Original Price          71699 non-null  float64
 2   Discounted Price        71699 non-null  float64
 3   Release Date            61394 non-null  datetime64[us]
 4   Link                    71699 non-null  str
 5   Game Description        71489 non-null  str
 6   Recent Reviews Summary  56480 non-null  str
 7   All Reviews Summary     5371 non-null   str
 8   Developer               71479 non-null  str
 9   Publisher               71183 non-null  str
 10  Supported Languages     71699 non-null  str
 11  Popular Tags            71699 non-null  str
 12  Game Features           71699 non-null  str
 13  Minimum Requirements    70576 non-null  str
 14  Discount Percentage     71699 non-null  float64
 15  Is Free                 71699 non-null  bool
 16  Release Year            61394 non-null  float64
 17  Release Month           61394 non-null  str
 18  Release Status          71699 non-null  str
 19  Release Month Number    61394 non-null  float64
 20  Recent Review %         37481 non-null  float64
 21  Recent Review Count     37481 non-null  float64
 22  All Review %            5371 non-null   float64
 23  All Review Count        5371 non-null   float64
dtypes: bool(1), datetime64[us](1), float64(9), str(13)
memory usage: 72.6 MB

In [50]:
steam_clean.to_csv(
    "../data/cleaned/steam_games_cleaned.csv",
    index=False
)

In [51]:
steam_clean['Release Year'] = steam_clean['Release Year'].astype('Int64')

steam_clean['Release Month Number'] = steam_clean['Release Month Number'].astype('Int64')

In [52]:
steam_clean.to_csv(
    "../data/cleaned/steam_games_cleaned.csv",
    index=False
)

In [54]:
steam_clean.dtypes

Title                                str
Original Price                   float64
Discounted Price                 float64
Release Date              datetime64[us]
Link                                 str
Game Description                     str
Recent Reviews Summary               str
All Reviews Summary                  str
Developer                            str
Publisher                            str
Supported Languages                  str
Popular Tags                         str
Game Features                        str
Minimum Requirements                 str
Discount Percentage              float64
Is Free                             bool
Release Year                       Int64
Release Month                        str
Release Status                       str
Release Month Number               Int64
Recent Review %                  float64
Recent Review Count              float64
All Review %                     float64
All Review Count                 float64
dtype: object

In [56]:
steam_clean.to_csv(
    "../data/cleaned/steam_games_cleaned.csv",
    index=False
)

In [57]:
steam_clean['Recent Review Count'] = steam_clean['Recent Review Count'].astype('Int64')

steam_clean['All Review Count'] = steam_clean['All Review Count'].astype('Int64')

In [58]:
steam_clean.to_csv(
    "../data/cleaned/steam_games_cleaned.csv",
    index=False
)

In [59]:
steam_clean.iloc[-1]

Title                                              Pixel Gun 3D: PC Edition
Original Price                                                          0.0
Discounted Price                                                        0.0
Release Date                                                            NaT
Link                      https://store.steampowered.com/app/2524890/Pix...
Game Description          Pixel Gun 3D is a near complete PC port of a l...
Recent Reviews Summary                                                  NaN
All Reviews Summary                                                     NaN
Developer                                                Cubic Games Studio
Publisher                                                Cubic Games Studio
Supported Languages       ['English', 'French', 'German', 'Japanese', 'K...
Popular Tags              ['Action', 'Shooter', 'Pixel Graphics', 'Battl...
Game Features             ['Single-player', 'Online PvP', 'Cross-Platfor...
Minimum Requirements      OS: |  Windows 10 (x64) - Windows 11 (x64) | P...
Discount Percentage                                                     0.0
Is Free                                                                True
Release Year                                                           <NA>
Release Month                                                           NaN
Release Status                                                  Coming Soon
Release Month Number                                                   <NA>
Recent Review %                                                         NaN
Recent Review Count                                                    <NA>
All Review %                                                            NaN
All Review Count                                                       <NA>
Name: 71699, dtype: object

In [60]:
steam_clean.to_csv(
    "../data/cleaned/steam_games_cleaned.csv",
    index=False,
    quoting=1
)

In [61]:
steam_clean.to_csv(
    "../data/cleaned/steam_games_cleaned.csv",
    index=False,
    na_rep="NULL"
)